project:
  type: website
  output-dir: docs

website:
  title: "Bahamas Water Level Sensor Project"
  site-url: https://github.com/palomacartwright/bahamas-sea-level-sensors
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data.qmd
        text: Data
      - href: sensors.qmd
        text: Sensors
     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



